### ISSUE TITLE
Clean up git repository

### ISSUE THREAD

**Issue by scastlara** [KucherenkoSerhiy/Microworld#17]
Right now, several binary and unnecessary files are being tracked by git. Someone has to spend some time removing them from the repository, without triggering a removal from the local repositories of all of us.

This has to be done on all branches (ideally on one branch, and then merged into all the others). 

Please, be careful.

**Comment by adriaaula** [comment]
Some logs still appear: 

`Microworld\Library\shadercompiler-UnityShaderCompiler.exe0.log`


This was generated.

**Comment by scastlara** [comment]
Are they on the git repository or only on your computers? Who `added` them? 

We only removed `modified` elements from the repository, maybe we skipped some unchanged **&** unwanted files...

We could remove them when they make an appeareance on our `git status` output; not a high priority, something we have to keep in mind. The important thing is to **never** `add` them again. When some file appears, we should `git rm --cached` them.

**Comment by adriaaula** [comment]
They are local, we didn't push. 

Hm, in the `.gitignore` example from this web they don't explicit any `.log` file. 


https://github.com/github/gitignore/blob/master/Unity.gitignore

**Comment by scastlara** [comment]
Everything under [Ll]ibrary is supposed to be ignored, so that does the trick. The problem is not the `.gitignore`, the problem is a `git add` **before** the `.gitignore` even existed. When something is tracked by git, even if you add it later to the `.gitignore`, that something will remain as a tracked file. That makes sense, it prevents something being removed because you fucked up the wildcards on your `.gitignore`. 

When I ask if it is on the `git` repository, I am not referring to github, but to **git**. So the question was not if you `git push`ed it, but if you (or someone) `git add`ed it.

**Comment by adriaaula** [comment]
So, probably someone added it! Cool
