### ISSUE TITLE
Die motherfucker

### ISSUE THREAD

**Issue by adriaaula** [KucherenkoSerhiy/Microworld#23]
Right now the GameObject of the P1 (and enemies controlled), when life goes to zero, only is deactivated. 

We want him dead. 

Or else we want the Game to restart with the P1 dead right now (afterwards this will probably change, but who cares).

**Comment by KucherenkoSerhiy** [comment]
"Die" és "La" en alemany. Pq hem de convertir un Character mort en versió femenina?
